#!/bin/bash
max=0
avg=0
n=0

#### Gotten from http://www.linuxjournal.com/content/floating-point-math-bash
float_scale=4

#####################################################################
# Evaluate a floating point number expression.

function float_eval()
{
    local stat=0
    local result=0.0
    if [[ $# -gt 0 ]]; then
        result=$(echo "scale=$float_scale; $*" | bc -q 2>/dev/null)
        stat=$?
        if [[ $stat -eq 0  &&  -z "$result" ]]; then stat=1; fi
    fi
    echo $result
    return $stat
}


#####################################################################
# Evaluate a floating point number conditional expression.

function float_cond()
{
    local cond=0
    if [[ $# -gt 0 ]]; then
        cond=$(echo "$*" | bc -q 2>/dev/null)
        if [[ -z "$cond" ]]; then cond=0; fi
        if [[ "$cond" != 0  &&  "$cond" != 1 ]]; then cond=0; fi
    fi
    local stat=$((cond == 0))
    return $stat
}
######


while read val
do
  ((n++))
  ((s=0))
  ((tmp=0))
  tmp=${val%%m*}
  ((s=tmp*60))
  tmp=${val##*m}
  tmp=${tmp%%s*}
  t=$(float_eval "$s + $tmp")
  if ((n==1))
  then
    min=$t
  else
    if float_cond "$t < $min"
    then
       min=$t
    fi
  fi
    
  if float_cond "$t > $max"
  then
    max=$t
  fi
  avg=$(float_eval "$avg + $t")
  echo "$n : $val min=$min max=$max avg=$avg"
done
 
avg=$(float_eval "$avg / $n")
echo "$avg $min $max"
 
