#!/bin/bash

dest=~/bin
install=( avg avgtm l2c livegraph myaliases dircolors:.dircolors)

if [[ ! -d $dest ]]; then
   mkdir -p $dest || echo "ERROR: mkdir $dest failed." >> /dev/stderr; exit -1 
fi

for f in ${install[@]}; do
    s=${f%%:*}
    d=${f##*:}
    if  [[ ! -a $dest/$d ]]; then
	cp -s $(realpath $s) $dest/$d
    else
	echo "Skipping install of $s to $dest/$d: already exists." >>/dev/stderr
    fi
done


if ! grep -q '~/bin/myaliases' ~/.bashrc; then
    cat >> ~/.bashrc  <<EOF
if [[ -a ~/bin/myaliases ]]; then
    . ~/bin/myaliases
fi
EOF
    echo "~/.bashrc updated"
else
    echo "Skipping update of ~/.bashrc as it seems to already"\
	 " have myaliases." >> /dev/stderr
fi
