#!/bin/bash
#set -x
destdir=~/bin
install=( avg avgtm l2c livegraph myaliases dircolors:~/.dircolors)

if [[ ! -d $destdir ]]; then
    mkdir -p $destdir ||
	echo "ERROR: mkdir $destdir failed." >> /dev/stderr; exit -1 
fi

for f in ${install[@]}; do
    s=${f%%:*}
    d=${f##*:}
    if [[ $s == $d ]]; then
	eval dest=$destdir/$d
    else
	eval dest=$d
    fi
    if  [[ ! -a $dest ]]; then
        cp -s $(realpath $s) $dest
    else
	echo "Skipping install of $s to $dest: already exists." >>/dev/stderr
    fi
done


if ! grep -q '~/bin/myaliases' ~/.bashrc; then
    cat >> ~/.bashrc  <<EOF
if [[ -a ~/bin/myaliases ]]; then
    . ~/bin/myaliases
fi
EOF
    echo "~/.bashrc updated"
else
    echo "Skipping update of ~/.bashrc as it seems to already"\
	 " have myaliases." >> /dev/stderr
fi
